### ISSUE TITLE
No input file specified. 

### ISSUE THREAD

**Issue by Axxon** [EtreRe/docker-compose-baseimage#1]
Hello, and thanks for share that code, but my first try result to a error "No input file specified. ", for http://localhost/, the image access work well. Could you try to tell me what's wrong ?

in log:

2015/03/22 16:04:08 [error] 26#0: *1 FastCGI sent in stderr: "Unable to open primary script: /home/http/localhost/app.php (No such file or directory)" while reading response header from upstream, client: 172.17.42.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.154:9000", host: "localhost"

it's seems that nginx container search php file on it's own and not in the fpm container.

For temp solution i add -v data/nginx:/home/http into nginx

**Comment by EtreRe** [comment]
Hello did you use docker-compose to create your container ?

Because your temp solution is in the .yml of docker-compose (in the volumes of nginx)

```
nginx:
  build: docker/nginx
  links:
    - phpfpm
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - config/nginx:/etc/nginx
    - log/nginx:/var/log/nginx
    - data/nginx:/home/http
```
